version: "3"
services:
  nginx:
    image: nginx:alpine  # The image name here is nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your nginx.conf
      - ./:/usr/share/nginx/html/
    ports:
      - "8080:80"  